// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/orders-section/OrderDetail.tsx": () => import("../components/mockups/orders-section/OrderDetail.tsx"),
  "./components/mockups/orders-section/OrdersList.tsx": () => import("../components/mockups/orders-section/OrdersList.tsx")
};
